---
title: Research on the Influence of Online Influencer live Streaming on the Purchase
  Intention of Customers
author: "Kaiwen Zhou"
date: "29/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(readr)
library(psych)
library(ggplot2)
library(knitr)


options(scipen = 999)


d_oils <- read_csv('../data_analysis_data.csv')

```

#demographic characteristic of this sample 

## gender
```{r}
d_oils %>%
  count(gender)

d_oils %>%
  ggplot(aes(x = gender)) + 
  geom_bar()

```
## Age 

```{R}
d_oils %>%
  count(age_range)


d_oils %>%
  ggplot(aes(x = age_range)) + 
  geom_bar()

```

## Descriptive statisitics : Likert items
```{r}

d_oils$A1 %>% median()

oils_likert_variable_median <- d_oils %>%
  select('Charm1','Charm2','Charm3','Interactivity1','Interactivity2','Interactivity3','Incentive1','Incentive2','Incentive3','Intention1','Intention2') %>%
  lapply(
    median
  )


d_oils_likert_variable_sammary <- tibble(
  Measurement_Question_Item = oils_likert_variable_median %>% names,
  Median = oils_likert_variable_median %>% unlist)

d_oils_likert_variable_sammary %>%
  ggplot(
    aes(x = Measurement_Question_Item, y = Median)
  ) +
  geom_point() +
  coord_flip()


        
```


#dummy variables & summary statistics

```{r}

d_oils <-d_oils %>%
  mutate(
    Female = gender == 'Female',
    Charmone = Charm1 >3 
  )

summary(d_oils$Female)

summary(d_oils$Charmone)

d_oils %>%
  xtabs(~Female + Charmone,.)  #contingence table#

d_oils %>%
  count(Female, Charmone)

d_oils %>%
  group_by(Female) %>%
  summarise(
    n = n(),
    Mdn = median(Charm1)
  )
 
d_oils %>%
  group_by(Female) %>%
  summarise(
    n = n(),
    Agree = sum(Charm1 > 3)) %>%
  mutate(
    Proportion = round(Agree / n * 100)
  )


```

# group scoring likert sacle

```{r}

keys_list <- list(
  Personal_Charm = c(
    'Charm1',
    'Charm2',
    'Charm3'
  ),
  Interactivity = c(
    'Interactivity1',
    'Interactivity2',
    'Interactivity3'
  ),
  Incentive = c(
    'Incentive1',
    'Incentive2',
    'Incentive3'
  ),
  Purchase_Intention = c(
    'Intention1',
    'Intention2'
  )
)

scoreItems(
  keys = keys_list,
  items = d_oils,
  totals = FALSE,
  missing = TRUE,
  impute = 'none'  
  
)     #对个变量的每组scale进行可信度打分


d_oils_scores <- scoreItems(
  keys = keys_list,
  items = d_oils,
  totals = FALSE,
  missing = TRUE,
  impute = 'none'  
  
) 

d_oils_scores$G6 #可信度score#

d_oils <- cbind(d_oils, d_oils_scores$scores)


```

#some more visualization

```{r}
d_oils %>%
  ggplot(aes(x = Purchase_Intention, fill = Female))+
  geom_histogram(binwidth = (0.5))



```

```{r}

d_oils %>%
  ggplot(aes(x = Personal_Charm, y=Purchase_Intention))+
  geom_point()

d_oils %>%
  ggplot(aes(x = Personal_Charm, y=Purchase_Intention, colour = Female))+
  geom_jitter()

```

#correlation  t-test 

```{r}

d_oils %>%
  t.test (
    Purchase_Intention ~ Female,
    var.equal = FALSE,
    data = .
  )


d_oils %>%
  mutate(Female = Female %>% as.numeric()) %>%
  cor.test(~ Purchase_Intention + Female, data=.)   # pearson correlation

   

d_oils %>%
  cor.test(~ Personal_Charm + Purchase_Intention, data=.)  #Personal_Charm

d_oils %>%
  cor.test(~ Interactivity + Purchase_Intention, data=.) #Interactivity

d_oils %>%
  cor.test(~ Incentive + Purchase_Intention, data=.) #Incentives


```


# liner model 单个变量

```{r}

d_oils %>%
  lm(Personal_Charm ~ Purchase_Intention, data =.) %>%
  summary()

d_oils %>%
  lm(Interactivity ~ Purchase_Intention, data =.) %>%
  summary()

d_oils %>%
  lm(Incentive ~ Purchase_Intention, data =.) %>%
  summary()


```


#liner model 多个变量

```{r}

d_oils %>%
  lm(Purchase_Intention ~ Personal_Charm + Interactivity + Incentive, data =.) %>%
  summary()


```